### ISSUE TITLE
The implementation of Dy-YOLOv7 is developed by the YOLOv7 [45] framework, with two identical detectors. The implementation of dynamic two-stage detectors is developed by the open-source CBNet [24] framework, with two identical backbones and a shared neck and head.

### ISSUE THREAD

**Issue by yahuyang** [VDIGPKU/DynamicDet#10]
![图片](https://github.com/VDIGPKU/DynamicDet/assets/73293451/aa879510-42ca-4fd1-98e9-7b2dcf59f72e)
作者您好，这句话什么意思呢？Dy-YOLOv7按照yolov7的框架包括了两个相同的yolov7检测器，动态两阶段检测器是按照CBNet的架构，包括两个相同的backbone和共享的neck和head是吧？那动态的两阶段检测器不符合DynamicDet的架构啊

**Comment by LZHgrla** [comment]
二阶段检测器的相关实验直接采用了CBNet所提出的共享neck&head，而在YOLOv7的相关实验我们使用了非共享neck&head，因为我们发现这会带来小幅度的精度涨幅。

整体来看，DynamicDet核心在于backbone个数的自适应选择，neck&head共享与否在此并不冲突

**Comment by yahuyang** [comment]
好的，非常感谢。
