### ISSUE TITLE
关于Dy-Faster R-CNN ResNet50和Dy-Mask R-CNN Swin-T配置文件

### ISSUE THREAD

**Issue by yahuyang** [VDIGPKU/DynamicDet#11]
作者您好，请问关于Dy-Faster R-CNN ResNet50和Dy-Mask R-CNN Swin-T的配置文件在哪里呀，代码中没找到

**Comment by LZHgrla** [comment]
这一部分的实验我们基于[CBNet代码](https://github.com/VDIGPKU/CBNetV2)，而非YOLO框架。由于二阶段检测器推理速度较慢，在实际应用较少，且我们暂时没有额外的精力进行整理，故没有开源。

如果您确实需要相关模型的支持，您可以尝试在[backbone部分](https://github.com/VDIGPKU/CBNetV2/blob/72334109d5d0c13ec1e8e8f8651f1a288e681c66/mmdet/models/backbones/cbnet.py#L286)和[loss部分](https://github.com/VDIGPKU/CBNetV2/blob/72334109d5d0c13ec1e8e8f8651f1a288e681c66/mmdet/models/detectors/two_stage.py#L212)进行修改。

**Comment by yahuyang** [comment]
好的，非常感谢！
