### ISSUE TITLE
关于Fig 7的疑问

### ISSUE THREAD

**Issue by yahuyang** [VDIGPKU/DynamicDet#12]
![image](https://github.com/VDIGPKU/DynamicDet/assets/73293451/e8668628-d314-490e-a0dc-ae6f3471f19e)
尊敬的作者：
       您好，Figure 7中，使用三种不同的优化策略训练的router，在以batch=1推理时，他们的推理时间为什么一样啊？还是说，固定住网络的推理时间和难易图像的分割比例，观察AP值的变化？

**Comment by LZHgrla** [comment]
正如您说的“固定住难易图像的分割比例”，分别是10%, 20%, 30%, ..., 90%。

**Comment by yahuyang** [comment]
router还是那个(SENet)，只不过优化的策略不一样，导致做出的“决策”的优劣不同，从而影响最终的AP,但是推理时间是一样的是吧，因为都是同一个router做的“决策”，可以这样理解吧？

**Comment by LZHgrla** [comment]
是的，没问题

**Comment by yahuyang** [comment]
好的，非常感谢
