### ISSUE TITLE
不好意思，您能帮我解决一下这个问题吗？

### ISSUE THREAD

**Issue by 1324039468** [VDIGPKU/DynamicDet#13]
![image](https://github.com/VDIGPKU/DynamicDet/assets/49754101/d27423a5-963a-49e8-9feb-bbcb738decc2)
这个报错信息 是哪里出了问题？

**Comment by 1324039468** [comment]
您好，之前都能够成功运行，怎么重新跑了一次啥也没改  就爆出这个错误？ 请求指教，谢谢您，万分感谢！

**Comment by LZHgrla** [comment]
https://github.com/VDIGPKU/DynamicDet/blob/4dbb9b258e8052f9ab8668a37387e55a88fa6f4b/train_step1.py#L302-L305

是不是打开了--single-backbone选项？应该走第304-305行这个分支，而非302-303

**Comment by 1324039468** [comment]
首先，非常感谢您的回复，请看我的测试，应该走的是304-305分支
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "VDIGPKU/DynamicDet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月8日(星期四) 晚上9:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [VDIGPKU/DynamicDet] 不好意思，您能帮我解决一下这个问题吗？ (Issue #13)





 
https://github.com/VDIGPKU/DynamicDet/blob/4dbb9b258e8052f9ab8668a37387e55a88fa6f4b/train_step1.py#L302-L305
 
是不是打开了--single-backbone选项？应该走第304-305行这个分支，而非302-303
