### ISSUE TITLE
关于训练adaptive router

### ISSUE THREAD

**Issue by yahuyang** [VDIGPKU/DynamicDet#14]
尊敬的作者：
       您好，请问在训练adaptive router时是如何进行监督的呢？

**Comment by LZHgrla** [comment]
直接使用论文中的Eq. (12), 
可参考：https://github.com/VDIGPKU/DynamicDet/blob/4dbb9b258e8052f9ab8668a37387e55a88fa6f4b/utils/loss.py#L572

**Comment by yahuyang** [comment]
好的，非常感谢。
还有，验证集大小不足时，验证集上的阈值并不能直接扩展到测试集上，这种情况下，我可以利用一定的方法进行估计嘛？

**Comment by LZHgrla** [comment]
我建议您可以尝试使用一部分训练集来统计阈值（虽然我们并未如此尝试过，但直觉上这是可行的），或者您可以直接从训练集切分一部分数据至验证集。

**Comment by yahuyang** [comment]
好的，谢谢您。
