### ISSUE TITLE
关于Variable-speed inference的疑问

### ISSUE THREAD

**Issue by yahuyang** [VDIGPKU/DynamicDet#15]
作者您好：
       
![image](https://github.com/VDIGPKU/DynamicDet/assets/73293451/0689176c-3abe-4b3e-9dbe-d73c1fc7928d)
通过(14)求出来的是分类为“hard”图像的比例，假如0.75，也就是75%的图像被分类为“hard”。那
![image](https://github.com/VDIGPKU/DynamicDet/assets/73293451/3a3a3b12-9737-4ce3-8864-947bb3c3473c)
计算的不应该是25%的分位数嘛，这样计算出来的阈值才有75%的图像的难度分数大于它呀。如果直接将0.75放进percentile函数，计算的好像不对啊
![image](https://github.com/VDIGPKU/DynamicDet/assets/73293451/898994dc-1e18-4f70-b80f-9c4ddbbc3f58)

**Comment by yahuyang** [comment]
![image](https://github.com/VDIGPKU/DynamicDet/assets/73293451/4ff781ef-90af-4cd3-8213-54bd4d2e84ee)
这里First和Second是不是弄反了呀，阈值越大，通过的“hard”图像越少的应该是Second啊

**Comment by LZHgrla** [comment]
https://github.com/VDIGPKU/DynamicDet/blob/4dbb9b258e8052f9ab8668a37387e55a88fa6f4b/models/yolo.py#L236-L245
That is, 'score' in our code denotes the (1 - difficulty score). So, it is ok~

**Comment by yangyahu-1994** [comment]
好的，我再看看代码哈

**Comment by yangyahu-1994** [comment]
作者您好：
score = self.router([y[i] for i in self.router_ins]) 计算出来的就是difficulty score啊，怎么会是1 - difficulty score呢？

**Comment by yahuyang** [comment]
> https://github.com/VDIGPKU/DynamicDet/blob/4dbb9b258e8052f9ab8668a37387e55a88fa6f4b/models/yolo.py#L236-L245
> 
> That is, 'score' in our code denotes the (1 - difficulty score). So, it is ok~

作者您好：
score = self.router([y[i] for i in self.router_ins]) 计算出来的就是difficulty score啊，怎么会是1 - difficulty score呢？ @LZHgrla

**Comment by LZHgrla** [comment]
https://github.com/VDIGPKU/DynamicDet/blob/4dbb9b258e8052f9ab8668a37387e55a88fa6f4b/models/yolo.py#L244-L245

分数足够低会选择second，分数足够高则会选择first。因此，这是由训练决定的，只要训练与推理统一即可。

**Comment by yahuyang** [comment]
> https://github.com/VDIGPKU/DynamicDet/blob/4dbb9b258e8052f9ab8668a37387e55a88fa6f4b/models/yolo.py#L244-L245
> 
> 分数足够低会选择second，分数足够高则会选择first。因此，这是由训练决定的，只要训练与推理统一即可。

![image](https://github.com/VDIGPKU/DynamicDet/assets/73293451/42d2ef8c-1274-4a8d-9a18-4bfddf4b53a2)
由这里决定？奖励的检测器乘的是1- difficulty score，所以拟合出来的score实际上是1- difficulty score？
那我把这里的score和1-score调换后，计算出来的score就表示difficulty score了吧？

**Comment by LZHgrla** [comment]
https://github.com/VDIGPKU/DynamicDet/blob/4dbb9b258e8052f9ab8668a37387e55a88fa6f4b/models/yolo.py#L244-L245
除了loss要修改，模型的forward也需要修改（分数足够大则走second，足够小则走first）。修改后即可认为score是difficulty score

**Comment by yahuyang** [comment]
> https://github.com/VDIGPKU/DynamicDet/blob/4dbb9b258e8052f9ab8668a37387e55a88fa6f4b/models/yolo.py#L244-L245
> 
> 除了loss要修改，模型的forward也需要修改（分数足够大则走second，足够小则走first）。修改后即可认为score是difficulty score

原来如此，感谢您的耐心解答。
