### ISSUE TITLE
关于Adaptive router计算的difficulty score

### ISSUE THREAD

**Issue by yahuyang** [VDIGPKU/DynamicDet#16]
作者您好：
          
![image](https://github.com/VDIGPKU/DynamicDet/assets/73293451/daaf740a-3c9e-4ecb-832c-aa17e210b207)
Adaptive router计算的输出为什么不是difficulty score而是1-difficulty score呢？

**Comment by LZHgrla** [comment]
duplicate https://github.com/VDIGPKU/DynamicDet/issues/15#issuecomment-1608683094
