### ISSUE TITLE
关于模型FLOPs和Parameters的计算

### ISSUE THREAD

**Issue by yahuyang** [VDIGPKU/DynamicDet#18]
![image](https://github.com/VDIGPKU/DynamicDet/assets/73293451/9e1b7738-6c25-4e1d-9b15-7a0d6d1c70c7)
尊敬的作者：
       您好，这里有两个FLOPs和Parameters，应该相信哪一个呢？

**Comment by Yshelgi** [comment]
一个fuse前,一个fuse后而已.

**Comment by yahuyang** [comment]
好的，非常感谢。
