### ISSUE TITLE
冒昧问一下大佬这个有什么前景/应用价值吗

### ISSUE THREAD

**Issue by feidufuzhou** [VDIGPKU/DynamicDet#19]
首先我可以将大佬的工作理解为：设计了一个可变计算量的网络吗，在easy图像下计算资源占用变少，在hard图片下计算资源占用变多。吗？
    如果是这样，那么在资源受限的设备上我一检测hard图片那么计算资源就不够了，在算力资源充足的设备上，既然有那么丰富的算力资源那么强的算力，我使用一个较为复杂的模型，对于hard和easy图片是不是都能以差不多的速度且较快地跑出来。
    请问这个的应用价值是什么？是为了在算力充足设备上多扣几毫秒时间吗。还是说比如说一台服务器，为别人远程提供检测任务，本来使用复杂模型我只能跑两个，现在我使用这种计算资源占用的模型我可以跑三个，多跑一个？
    望大佬解答，谢谢！

**Comment by LZHgrla** [comment]
一个动态检测器，在同样的资源下，可以通过调整阈值以调整easy、hard的比例，进而满足不同的时延需求

一个简单的示例是：一个训好的检测器，既可以部署到资源充足的设备，也可部署到资源受限的设备，并且仅需通过调整阈值就可以调整其时延

**Comment by feidufuzhou** [comment]
> 一个动态检测器，在同样的资源下，可以通过调整阈值以调整easy、hard的比例，进而满足不同的时延需求
> 
> 一个简单的示例是：一个训好的检测器，既可以部署到资源充足的设备，也可部署到资源受限的设备，并且仅需通过调整阈值就可以调整其时延

好的谢谢
