### ISSUE TITLE
您好，没有在您分享的代码中找到关于Resnet网络的代码，可以提供这一部分的代码吗？

### ISSUE THREAD

**Issue by chenxlin222** [VDIGPKU/DynamicDet#20]
您好，没有在您分享的代码中找到关于Resnet网络的代码，可以提供这一部分的代码吗？

**Comment by LZHgrla** [comment]
这一部分代码因为并未进行整理，所以并未开源，如果确有需要可以在CBNet的基础上增加 Router 和 训练 Loss，具体可见https://github.com/VDIGPKU/DynamicDet/issues/11
