### ISSUE TITLE
您好，想请问一下原文中公式13的问题

### ISSUE THREAD

**Issue by CZY-Code** [VDIGPKU/DynamicDet#21]
原文中Δ=L1-L2吗？如果是那么公式13的右边L1-L2-Δ应该是等于零？那么梯度下降呢

**Comment by LZHgrla** [comment]
@CZY-Code 
L1、L2是当前样本的loss
而Δ是整个训练集（或很多很多样本）的L1-L2的中位数
因此并不是零

**Comment by CZY-Code** [comment]
OK，谢谢
