### ISSUE TITLE
Config for custom data

### ISSUE THREAD

**Issue by mansi-aggarwal-2504** [VDIGPKU/DynamicDet#24]
Hello,
My dataset has only one object - I have modified the coco.yaml file accordingly to give data paths, nc = 1 and my class name (which in represented by 0 in the txt files). 

Apart from that, do I need to alter any other cfg/hyp files? 
I see cfg/dy-yolov7-step1.yaml has an nc variable which I think I would change. Any other changes that I’d need to make?

**Comment by LZHgrla** [comment]
Hi! I think these modifications have adequately met the requirements.

**Comment by mansi-aggarwal-2504** [comment]
That means I have to change the cfg/dy-yolov7-step1.yaml file right?

**Comment by LZHgrla** [comment]
Yeah
change `cfg/...` to modify the model, and change `data/...` to modify the data information
