### ISSUE TITLE
Early stopping or using epoch_xx.pt

### ISSUE THREAD

**Issue by mansi-aggarwal-2504** [VDIGPKU/DynamicDet#25]
Hello,

Is there an early stopping mechanism for DynamicDet? Alternately, could I use intermediate weights in `runs/train/weights` like `epoch_xx.pt` for `train_step2` and inference?

Thanks.

**Comment by LZHgrla** [comment]
1. We developed DynamicDet based on [yolov7](https://github.com/WongKinYiu/yolov7), and we did not introduce early stop feature. I also believe that YOLOv7 does not have an early stop feature.
2. You can use any `epoch_xx.pth` for `train_step2`. But I think you need first run `strip_optimizer` for this weight
```python
from utils.general import strip_optimizer
strip_optimizer('YOUR_WEIGHT_PATH')
```

**Comment by mansi-aggarwal-2504** [comment]
Hi, thanks for your reply!

I did that on my `last.pt` weight as I stopped training after 90 epochs as my training had been running for 48+ hours and I am still getting an error while running `train_step2.py`:

```
 File "DynamicDet/train_step2.py", line 548, in <module>
    train(hyp, opt, device, tb_writer)
  File "DynamicDet/train_step2.py", line 160, in train
    optimizer.load_state_dict(ckpt['optimizer'])
  File "/envs/dynamicdet_evn/lib/python3.7/site-packages/torch/optim/optimizer.py", line 141, in load_state_dict
    raise ValueError("loaded state dict has a different number of "
ValueError: loaded state dict has a different number of parameter groups
```

What am I doing wrong?
