### ISSUE TITLE
想请教下论文中优化策略的自适应偏差问题

### ISSUE THREAD

**Issue by 781458112** [VDIGPKU/DynamicDet#3]
想请教下这个平衡点是如何计算的，在实际应用中我们如何确定中等难度的图像是哪一种？也就是图5中的黄色点位置是如何找到的？期待您的回答。

**Comment by LZHgrla** [comment]
平衡点 $\Delta$ 等于级联的两组目标检测器在**训练集数据上的loss差的中位数**，可以离线获得（直接统计所有训练集数据的loss差，求中位数），也可以在训练router时动态获取（如[link](https://github.com/VDIGPKU/DynamicDet/blob/4dbb9b258e8052f9ab8668a37387e55a88fa6f4b/utils/loss.py#LL683C14-L683C14))
