### ISSUE TITLE
请问有提供权重文件吗？

### ISSUE THREAD

**Issue by SSZ1** [VDIGPKU/DynamicDet#4]
请问开源项目里有提供权重文件吗？dy-yolov7.pt

**Comment by LZHgrla** [comment]
有的
https://github.com/VDIGPKU/DynamicDet/releases/tag/v0.1

**Comment by SSZ1** [comment]
> 有的 https://github.com/VDIGPKU/DynamicDet/releases/tag/v0.1

谢谢！
