### ISSUE TITLE
Can it be extended to anchor-free detectors?

### ISSUE THREAD

**Issue by yahuyang** [VDIGPKU/DynamicDet#7]
Dear Author:
Hello, first of all, thank you for your excellent work.
You say “This dynamic architecture can be easily adapted to mainstream detectors, e.g., Faster R-CNN and YOLO”, I was wondering if it could be extended to anchor-free detectors such as CornerNet and CenterNet.

**Comment by LZHgrla** [comment]
Hi, @yangyahu-1994 
Theoretically, our approach is orthogonal to anchor-free or anchor-based architectures. 
Thus, we believe that it can be extended to anchor-free detectors. However, we have not conducted relevant experiments.

Please feel free to provide feedback if you have any further questions!

**Comment by yahuyang** [comment]
OK, thanks very much.
![image](https://github.com/VDIGPKU/DynamicDet/assets/73293451/baeddf08-a596-438d-bb5a-aa7fe1e9cb92)
In equation (14), $lat_t$ is defined as the target latency, that is, it is the latency of a specific object, such as an autonomous vehicle or a mobile phone, thus allowing for different accuracy-speed trade-offs under different hardware constraints? Can I understand it this way?

**Comment by LZHgrla** [comment]
Yes!

**Comment by yahuyang** [comment]
Thank you very much!
